name: archive
version: 2.0.13
description: Provides encoders and decoders for various archive and compression formats such as zip, tar, bzip2, gzip, and zlib.
homepage: https://github.com/brendan-duncan/archive
environment:
  sdk: '>=2.10.0-110.5.beta <2.11.0'
documentation: https://github.com/brendan-duncan/archive/wiki
dependencies:
  crypto: '>=2.1.5 <3.0.0'
  args: '>=1.4.0 <2.0.0'
  path: '>=1.7.0 <2.0.0'
dev_dependencies:
  test: '>=1.15.4 <2.0.0'
  build_web_compilers: '>=2.12.1 <3.0.0'
  build_runner: '>=1.10.3 <2.0.0'
  pedantic: ^1.0.0
